### ISSUE TITLE
非常用心的文档，可惜没有更了

### ISSUE THREAD

**Issue by HeyDavid633** [hyfshishen/understanding-llvm-transformation-passes#1]

**Comment by hyfshishen** [comment]
Hi, 其实我有写完的版本（分析了很多pass，不过比较潦草，算是个个人笔记版本），但是一直没有更新在这个doc里。可以告诉我您的邮箱吗，如果需要的话我可以分享一下。

**Comment by HeyDavid633** [comment]
太好了，感谢您的分享，这会对我们团队的同学学习会有很大的帮助😋 
我的个人邮箱是 wenhao.dai@student.cup.edu.cn 非常期待和您的交流🤩

**Comment by hyfshishen** [comment]
Just done updating this document. So this issue will be closed.
